server:
  port: 80
spring:
  application:
    name: consumer
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8081/eureka
feign:
  compression:
    request:
      # 配置请求GZIP压缩
      enabled: true
      # 配置压缩支持的MIME TYPE
      mime-types: text/xml,application/xml,application/json
      # 配置压缩数据大小的下限
      min-request-size: 2048
      # 配置响应GZIP压缩
    response:
      enabled: true
  hystrix:
    enabled: true

ribbon:
  # 处理请求的超时时间，默认为1秒
  ReadTimeout: 60000
  # 连接建立的超时时长，默认1秒
  ConnectTimeout: 60000
  # 同一台实例的最大重试次数，但是不包括首次调用，默认为1次
  MaxAutoRetries: 1
  # 重试负载均衡其他实例的最大重试次数，不包括首次调用，默认为0次
  MaxAutoRetriesNextServer: 0